on: push
name: Lint all Dockerfiles
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Linter
      uses: docker://cdssnc/docker-lint-github-action
      with:
        args: --ignore DL3018
